name = "MusicFromBirds"
uuid = "06962e27-4ff1-49f9-874f-af87d05cc986"
authors = ["ardy-monaghan <ross.monaghan99@gmail.com>"]
version = "0.1.0"

[deps]
BlobTracking = "738e0a8b-9125-4fc4-8d4f-3a5b1a21603b"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
VideoIO = "d6d074c3-1acf-5d4c-9a43-ef38773959a2"

[compat]
BlobTracking = "0.2.1"
Images = "0.25.3"
VideoIO = "1.4.0"
